### ISSUE TITLE
[API improvement] Types of params of PreparedStatement in Query or Update 

### ISSUE THREAD

**Issue by BillyYccc** [vietj/vertx-pg-client#24]
#### Status
Currently query or update in [PgOperations](https://github.com/vietj/vertx-pg-client/blob/master/src/main/java/com/julienviet/pgclient/PgOperations.java) use `List<Object>` to hold multiple params, API is something like this `void query(String sql, List<Object> params, Handler<AsyncResult<ResultSet>> handler);`
 or `void update(String sql, List<Object> params, Handler<AsyncResult<UpdateResult>> handler);`

#### Motivation
As it's defined in [vertx-sql-common](https://github.com/vert-x3/vertx-sql-common), [SQLOperations](https://github.com/vert-x3/vertx-sql-common/blob/master/src/main/java/io/vertx/ext/sql/SQLOperations.java) use `JsonArray` to hold mutiple params like `SQLOperations queryWithParams(String sql, JsonArray params, Handler<AsyncResult<ResultSet>> resultHandler);` 
or `SQLOperations updateWithParams(String sql, JsonArray params, Handler<AsyncResult<UpdateResult>> resultHandler);`
It's better to keep consistency, is it right?

Apart from this, `List<Object>` is also not supported by Codegen when passing as input parameters, so the method has to be ignored by `@GenIgnore`. When using Rxi-fied API, there is no methods to take multiple params as one collection, users have to maintain a state of how many params they use and then choose which method to use, this is not convenient when facing dynamic SQLs.

Therefore is there any possibility to change this?

**Comment by vietj** [comment]
I think we should work out in vertx the ability to support List<Object> and use it

**Comment by vietj** [comment]
@BillyYccc the master has been updated to use a `Tuple` object that is now available in RxJava as well, would you mind to try it ?

**Comment by BillyYccc** [comment]
@vietj Thanks for your nicely effort, This works now!
